# Generated by Django 5.1.3 on 2025-01-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_giornalista_anno_di_nascita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='data',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
