# Generated by Django 5.1.3 on 2025-02-26 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_articolo_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 26, 10, 9, 52, 5089)),
        ),
        migrations.AlterField(
            model_name='giornalista',
            name='anno_di_nascita',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 26, 10, 9, 52, 5089), max_length=10),
        ),
    ]
