# Generated by Django 5.1.4 on 2025-04-01 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_articolo_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 1, 17, 53, 8, 23746)),
        ),
        migrations.AlterField(
            model_name='giornalista',
            name='anno_di_nascita',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 1, 17, 53, 8, 23488), max_length=10),
        ),
    ]
