# Generated by Django 5.1.4 on 2025-02-18 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('data_inizio', models.DateField(blank=True, default=datetime.datetime(2025, 2, 18, 16, 51, 26, 477059))),
                ('data_fine', models.DateField(blank=True, default=datetime.datetime(2025, 2, 18, 16, 51, 26, 477069))),
                ('posti_disponibili', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Corso',
                'verbose_name_plural': 'Corsi',
            },
        ),
    ]
