# Generated by Django 5.1.3 on 2025-02-26 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('data_inizio', models.DateField(blank=True, default=datetime.datetime(2025, 2, 26, 9, 33, 46, 378750))),
                ('data_fine', models.DateField(blank=True, default=datetime.datetime(2025, 2, 26, 9, 33, 46, 378750))),
                ('posti_disponibili', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventi',
            },
        ),
    ]
