# Generated by Django 5.1.3 on 2025-02-26 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_culturali', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='descrizione',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_fine',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 26, 10, 9, 52, 18412)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inizio',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 26, 10, 9, 52, 18412)),
        ),
    ]
