# Generated by Django 5.1.3 on 2025-03-19 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_culturali', '0002_evento_descrizione_alter_evento_data_fine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_fine',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 19, 11, 21, 51, 416304)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inizio',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 19, 11, 21, 51, 416304)),
        ),
    ]
