# Generated by Django 5.1.4 on 2025-04-01 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi_culturali', '0004_alter_evento_data_fine_alter_evento_data_inizio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_fine',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 1, 17, 53, 8, 24360)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inizio',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 1, 17, 53, 8, 24351)),
        ),
    ]
